<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Booking Confirmation - Online Tour Planner</title>

    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        body {
            background: #f5f7fb;
            color: #172033;
            min-height: 100vh;
        }

        header {
            height: 75px;
            padding: 0 8%;
            background: white;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 2px 15px rgba(0, 0, 0, 0.08);
        }

        header h1 {
            color: #172554;
            font-size: 24px;
        }

        nav a {
            color: #333;
            text-decoration: none;
            margin-left: 25px;
            font-weight: 500;
            transition: 0.3s;
        }

        nav a:hover {
            color: #2563eb;
        }

        .confirmation-container {
            width: 90%;
            max-width: 650px;
            margin: 70px auto;
            text-align: center;
        }

        .confirmation-card {
            background: white;
            padding: 45px 35px;
            border-radius: 16px;
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.08);
        }

        .success-icon {
            width: 90px;
            height: 90px;
            margin: 0 auto 25px;
            border-radius: 50%;
            background: #dcfce7;
            color: #16a34a;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 50px;
            animation: pop 0.6s ease;
        }

        @keyframes pop {
            0% {
                transform: scale(0);
            }

            70% {
                transform: scale(1.15);
            }

            100% {
                transform: scale(1);
            }
        }

        h2 {
            color: #172554;
            font-size: 32px;
            margin-bottom: 12px;
        }

        .message {
            color: #666;
            margin-bottom: 30px;
        }

        .booking-details {
            background: #f8fafc;
            padding: 20px;
            border-radius: 10px;
            text-align: left;
            margin-bottom: 30px;
        }

        .detail {
            display: flex;
            justify-content: space-between;
            padding: 12px 0;
            border-bottom: 1px solid #e2e8f0;
        }

        .detail:last-child {
            border-bottom: none;
        }

        .detail span:first-child {
            color: #64748b;
        }

        .detail span:last-child {
            font-weight: 600;
            color: #172033;
        }

        .booking-id {
            color: #2563eb !important;
        }

        .buttons {
            display: flex;
            justify-content: center;
            gap: 12px;
            flex-wrap: wrap;
        }

        .button {
            display: inline-block;
            padding: 12px 22px;
            border-radius: 7px;
            text-decoration: none;
            background: #172554;
            color: white;
            transition: 0.3s;
        }

        .button:hover {
            background: #2563eb;
            transform: translateY(-3px);
            box-shadow: 0 8px 20px rgba(37, 99, 235, 0.2);
        }

        .secondary-button {
            background: #e2e8f0;
            color: #172033;
        }

        .secondary-button:hover {
            background: #cbd5e1;
        }

        @media (max-width: 600px) {
            header {
                padding: 0 5%;
            }

            nav a {
                margin-left: 10px;
            }

            .confirmation-container {
                margin-top: 40px;
            }
        }
    </style>
</head>

<body>

<header>

    <h1>Online Tour Planner</h1>

    <nav>
        <a href="userHome.jsp">Dashboard</a>
        <a href="myBookings.jsp">My Bookings</a>
        <a href="LogoutServlet">Logout</a>
    </nav>

</header>

<main class="confirmation-container">

    <div class="confirmation-card">

        <div class="success-icon">
            ✓
        </div>

        <h2>Booking Confirmed!</h2>

        <p class="message">
            Your booking has been successfully confirmed.
        </p>

        <div class="booking-details">

            <div class="detail">
                <span>Booking ID</span>
                <span class="booking-id">Generated by system</span>
            </div>

            <div class="detail">
                <span>Service</span>
                <span>Will be loaded</span>
            </div>

            <div class="detail">
                <span>Destination</span>
                <span>Will be loaded</span>
            </div>

            <div class="detail">
                <span>Status</span>
                <span>Confirmed</span>
            </div>

        </div>

        <div class="buttons">

            <a href="myBookings.jsp" class="button">
                View My Bookings
            </a>

            <a href="userHome.jsp" class="button secondary-button">
                Dashboard
            </a>

        </div>

    </div>

</main>

</body>
</html>